//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID_Car { get; set; }
        public int Brand_ID { get; set; }
        public string Years { get; set; }
        public decimal Price { get; set; }
    
        public virtual Brands Brands { get; set; }
    }
}
